import unittest

class TestDimension(unittest.TestCase):
    pass

    # TODO : import benchmarks and test that they run (no fail assertion)
    # def run_test(self):
    #     try:
    #         myFunc()
    #     except ExceptionType:
    #         self.fail("myFunc() raised ExceptionType unexpectedly!")